### ISSUE TITLE
Please provide a live demo

### ISSUE THREAD

**Issue by manuel-burato** [Code-Crash/cc-terminal#2]
Hi really want to try your project but atm I cannot set up a project to test it. Could you provide a live demo so new user can try it and compare with other similar solutions?

Have a nice day
M

**Comment by Code-Crash** [comment]
Hi @manuel-burato ,

Thanks for the note, apologies for the delay in response, sure, I will create a small live example.

**Comment by Code-Crash** [comment]
I have updated a read me with the demo link, also please find here: https://codesandbox.io/s/03w0sg

will be closing the thread, let me know if there is any suggestion or need any kind of clarafication.
